config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :slides
  root 'welcome#index'

end

app/models/slide.rb
class Slide < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
	protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
	def new 
		@slide = Slide.new
	end
	
	def index
		@slides = Slide.all
		respond_to do |format|
			format.json { render json: @slides}
		end
	end

	def show
		@slide = Slide.find(params[:id])
		respond_to do |format|
			format.json { render json: @slide}
		end
	end

	def create
		@slide = Slide.new(slide_params)
		
		Slide.where("position >= ?", @slide.position).each do |slide| 
			slide.position = slide.position+1
			slide.save
		end
		
		@slide.save!
		
		respond_to do |format|
			format.json { render json: @slide}
		end 
	end

	def update
		@slide = Slide.find(params[:id])
		@slide.update_attributes(slide_params)
		respond_to do |format|
			format.json { render json: @slide}
		end
	end

	def destroy
		@slide = Slide.find(params[:id])
		Slide.where("position > ?", @slide.position).each do |slide|
			slide.position = slide.position-1
			slide.save
		end
		@slide.destroy
		respond_to do |format|
			format.json { head :no_content }	
		end
	end

	private
	  def slide_params
	    params.require(:slide).permit(:title, :content, :position)
	  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>React</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/slides/index.html.erb
 <div>
 <% @slides.each do |slide| %>
 	<div><span><%slide.title%></span>&nbsp;&nbsp;<span><%slide.content%></span>&nbsp;&nbsp;<span><%slide.position%></span></div>
 <%end%>
 </div>

app/views/slides/new.html.erb
<%= form_for :slide, url: slides_path do |f| %>
 
  <% if @slide.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@slide.errors.count, "error") %> prohibited
        this slide from being saved:
      </h2>
      <ul>
        <% @slide.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
 
  <p>
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/slides/show.html.erb
<p>Title: <%=@slide.title%></p>
<p>Content: <%=@slide.content%></p>
<p>Position: <%=@slide.position%></p>